# Generated by Django 4.2.5 on 2024-12-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='QuantityPerCarton',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix_livraison',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix_vente_kit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prix_vente_pc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reforme',
        ),
    ]
