# Generated by Django 4.2.5 on 2024-12-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_remove_product_quantitypercarton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reforme',
            field=models.BooleanField(default=False),
        ),
    ]
