# Generated by Django 4.2.5 on 2024-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_product_reforme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
