# Generated by Django 4.2.5 on 2024-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_product_prix_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix_vente_pc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
