# Generated by Django 4.2.5 on 2024-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_product_prix_vente_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='QuantityPerCarton',
            field=models.IntegerField(default=0),
        ),
    ]
