# Generated by Django 4.2.5 on 2024-12-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_product_parent_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='MotherCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='category',
            name='kitcomponents',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pc_component',
        ),
    ]
