# Generated by Django 4.2.5 on 2024-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_remove_category_mothercategory_remove_category_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pc_component',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
