# Generated by Django 4.2.5 on 2024-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_category_pc_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kit',
            field=models.BooleanField(default=True),
        ),
    ]
