# Generated by Django 4.2.5 on 2024-12-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='AIDoc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Nif',
        ),
        migrations.RemoveField(
            model_name='client',
            name='NifDoc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Nis',
        ),
        migrations.RemoveField(
            model_name='client',
            name='NisDoc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='RCDoc',
        ),
        migrations.RemoveField(
            model_name='client',
            name='num_article',
        ),
        migrations.RemoveField(
            model_name='client',
            name='region_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sourceClient',
        ),
        migrations.RemoveField(
            model_name='client',
            name='valide',
        ),
    ]
