# Generated by Django 4.2.5 on 2024-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_remove_client_aidoc_remove_client_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Nif',
            field=models.CharField(default='', max_length=150),
        ),
    ]
