# Generated by Django 4.2.5 on 2024-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0005_client_nis'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_article',
            field=models.CharField(default='', max_length=150),
        ),
    ]
