# Generated by Django 4.2.5 on 2024-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0006_client_num_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='region_client',
            field=models.CharField(default='', max_length=150),
        ),
    ]
