# Generated by Django 4.2.5 on 2024-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0007_client_region_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sourceClient',
            field=models.CharField(default='', max_length=150),
        ),
    ]
