# Generated by Django 4.2.5 on 2024-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0008_client_sourceclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='AIDoc',
            field=models.FileField(null=True, upload_to='media/document'),
        ),
    ]
