# Generated by Django 4.2.5 on 2024-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0011_client_nisdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='RCDoc',
            field=models.FileField(null=True, upload_to='media/document'),
        ),
    ]
