# Generated by Django 4.2.5 on 2024-12-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0012_client_rcdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='valide',
            field=models.BooleanField(default=True),
        ),
    ]
