# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_customgroup_store_customuser_employeeat_equipe_store'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BonComptoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('observation', models.CharField(blank=True, default='', max_length=4500, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalremise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonRectification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('observation', models.CharField(blank=True, default='', max_length=4500, null=True)),
                ('totalprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalremise', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonRetourComptoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('decision', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.TextField(blank=True, default='', null=True)),
                ('lieu', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('type_reglement', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True, default='', null=True)),
                ('Téléphone', models.TextField(blank=True, default='', null=True)),
                ('fidelite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonComptoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonRectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='verssement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date', models.DateField()),
                ('bon_comptoir_associe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verssements', to='comptoire.boncomptoire')),
                ('bon_rectification_associe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verssements', to='comptoire.bonrectification')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('utilisateur', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonRetourComptoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retourcomptoir', to='comptoire.bonretourcomptoir')),
            ],
        ),
    ]
