# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptoire', '0001_initial'),
        ('produits', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretourcomptoir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retourcomptoir', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_rectification', to='comptoire.bonrectification'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_rectification', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='produitsenbonrectif',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_rectif', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_comptoir', to='comptoire.boncomptoire'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_boncomp', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='produitsenboncomptoir',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_comptoir', to='produits.product'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_points_ventes', to='inventory.entrepot'),
        ),
    ]
