# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('reglements', '0001_initial'),
        ('user', '0004_customgroup_store_customuser_employeeat_equipe_store'),
        ('comptoire', '0002_initial'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointvente',
            name='mode_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointVentes', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='pointvente',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='cloture',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='cloture',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='bon_comptoir_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_compt', to='comptoire.boncomptoire'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='bon_rectification_associe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_retour_compt', to='comptoire.bonrectification'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsretour_compt', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonretourcomptoir',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retourcomptoire', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesbons_rectification', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='pointVente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_rectif_store', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonrectification',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_rectification', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesbons_comptoir', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='pointVente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_comptoir_store', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='boncomptoire',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_comptoire', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='affectationcaisse',
            name='CompteTres',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='affectationcaisse',
            name='emplacement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_affectation', to='comptoire.pointvente'),
        ),
        migrations.AddField(
            model_name='affectationcaisse',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='affectationcaisse',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_affectation', to='user.customuser'),
        ),
    ]
