# Generated by Django 4.2.5 on 2024-12-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0002_initial'),
        ('tiers', '0001_initial'),
        ('reglements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_reglements', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_typefournisseur', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='reglementfournisseur',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
