# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0002_initial'),
        ('user', '0001_initial'),
        ('tiers', '0001_initial'),
        ('ventes', '0001_initial'),
        ('reglements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementfournisseur',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='BonS',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonS_reglements', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='CompteEntreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reglements', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='facture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_reglements', to='ventes.facture'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='montantSource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_reglements', to='reglements.historiquemontantrecuperer'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='reglement',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='CompteEntreprise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='CompteEntrepriseDestinataire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_recu', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='mouvementcaisse',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='montantcollected',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montantcollected_reg', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='montantcollected',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='montantcollected',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='modereglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='historiquemontantrecuperer',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montant_envoye', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='echeancereglement',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='depense',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='depense',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglement_depense', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='depense',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='depense',
            name='type_depense',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_depenses', to='reglements.typedepense'),
        ),
        migrations.AddField(
            model_name='depense',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='cloturereglements',
            name='caisse',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clotures_reg', to='clientInfo.compteentreprise'),
        ),
        migrations.AddField(
            model_name='cloturereglements',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='cloturereglements',
            name='utilisateur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
    ]
