# Generated by Django 4.2.5 on 2025-01-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='montantSource',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='note',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='num_cheque',
        ),
        migrations.RemoveField(
            model_name='reglement',
            name='piece_jointe',
        ),
    ]
