# Generated by Django 4.2.5 on 2025-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0004_remove_reglement_montantsource_remove_reglement_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='pj'),
        ),
    ]
