# Generated by Django 4.2.5 on 2025-01-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0005_reglement_piece_jointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='num_cheque',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
