# Generated by Django 4.2.5 on 2025-01-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0006_reglement_num_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='montantSource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rep_reglements', to='reglements.historiquemontantrecuperer'),
        ),
    ]
