# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('clientInfo', '0002_initial'),
        ('gestionRH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='requetesalarie',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='requetesalarie',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='renumeration',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='reglementcompte',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_reglementscompte', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='prixsocial',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_prox_social', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='primemotivation',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_primesmotivation', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_pointage', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='heuresup',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_heure_sup', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='heuresup',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='heuresup',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ma_contrat', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='conge',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mon_conge', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='avancesalaire',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_avances_salaire', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='absence',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_absences', to='gestionRH.salarie'),
        ),
        migrations.AddField(
            model_name='absence',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='absence',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
    ]
