# Generated by Django 4.2.5 on 2025-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='association',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='ccp',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='dateEnd',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='datenaiss',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='degre',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='echellon',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='fonctionarabe',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='lieu_naissancearabe',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='nomarabe',
        ),
        migrations.RemoveField(
            model_name='salarie',
            name='num_assurancesocial',
        ),
    ]
