# Generated by Django 4.2.5 on 2025-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0003_remove_salarie_association_remove_salarie_ccp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='association',
            field=models.CharField(default='', max_length=255),
        ),
    ]
