# Generated by Django 4.2.5 on 2025-01-08 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0005_salarie_ccp'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='datenaiss',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
