# Generated by Django 4.2.5 on 2025-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0012_salarie_nomarabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='num_assurancesocial',
            field=models.CharField(default='', max_length=255),
        ),
    ]
