# Generated by Django 4.2.5 on 2025-01-08 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0013_salarie_num_assurancesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='dateDebut',
            field=models.DateField(default=datetime.datetime.now, help_text='The date of start.'),
        ),
    ]
