# Generated by Django 4.2.5 on 2025-01-08 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0014_salarie_datedebut'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime.now, help_text='The date of start.'),
        ),
    ]
