# Generated by Django 4.2.5 on 2025-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0015_salarie_dateend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='type_conge',
        ),
    ]
