# Generated by Django 4.2.5 on 2025-01-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0016_remove_conge_type_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='type_conge',
            field=models.TextField(default=''),
        ),
    ]
