# Generated by Django 4.2.5 on 2025-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0018_remove_absence_minussource'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='minusSource',
            field=models.CharField(default='', max_length=255),
        ),
    ]
