# Generated by Django 4.2.5 on 2025-01-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0019_absence_minussource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primemotivation',
            name='viremenet',
        ),
    ]
