# Generated by Django 4.2.5 on 2025-01-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionRH', '0020_remove_primemotivation_viremenet'),
    ]

    operations = [
        migrations.AddField(
            model_name='primemotivation',
            name='viremenet',
            field=models.BooleanField(default=True),
        ),
    ]
