# Generated by Django 5.1.4 on 2024-12-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0001_initial'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteentreprise',
            name='agence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_comptes', to='tiers.agence'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='banque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_comptes', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='compteComptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptable_compteEntreprise', to='clientInfo.plancomptableaccount'),
        ),
        migrations.AddField(
            model_name='plancomptableaccount',
            name='comptable_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientInfo.plancomptableclass'),
        ),
        migrations.AddField(
            model_name='devise',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_devise', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_comptes', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_taxes', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='typeclient',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_typeClient', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='valeurdevise',
            name='Devise',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.devise'),
        ),
        migrations.AddField(
            model_name='valeurdevise',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_devises_valeur', to='clientInfo.store'),
        ),
    ]
