# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('clientInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteentreprise',
            name='agence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_comptes', to='tiers.agence'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='banque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_comptes', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='compteComptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptable_compteEntreprise', to='clientInfo.plancomptableaccount'),
        ),
        migrations.AddField(
            model_name='compteentreprise',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_comptes', to='clientInfo.store'),
        ),
    ]
