# Generated by Django 4.2.5 on 2024-12-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='articleImpo',
        ),
        migrations.RemoveField(
            model_name='store',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='store',
            name='capitaleSocial',
        ),
        migrations.RemoveField(
            model_name='store',
            name='code',
        ),
        migrations.RemoveField(
            model_name='store',
            name='compteBancaire',
        ),
        migrations.RemoveField(
            model_name='store',
            name='compteCCP',
        ),
        migrations.RemoveField(
            model_name='store',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='store',
            name='fax1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='fax2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='fax3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='identifiantStatistique',
        ),
        migrations.RemoveField(
            model_name='store',
            name='mobile1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='mobile2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='mobile3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='monnaie',
        ),
        migrations.RemoveField(
            model_name='store',
            name='nAdherent',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone3',
        ),
        migrations.RemoveField(
            model_name='store',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='store',
            name='raisonSocial',
        ),
        migrations.RemoveField(
            model_name='store',
            name='registreCom',
        ),
    ]
