# Generated by Django 4.2.5 on 2024-12-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0003_remove_store_address1_remove_store_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address3',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
