# Generated by Django 4.2.5 on 2024-12-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0004_store_address1_store_address2_store_address3'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='articleImpo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
