# Generated by Django 4.2.5 on 2024-12-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0007_store_capitalesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
