# Generated by Django 4.2.5 on 2024-12-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0008_store_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='compteBancaire',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
