# Generated by Django 4.2.5 on 2024-12-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0011_store_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fax1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='fax2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='fax3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
