# Generated by Django 4.2.5 on 2024-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0012_store_fax1_store_fax2_store_fax3'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='identifiantStatistique',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
