# Generated by Django 4.2.5 on 2024-12-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0013_store_identifiantstatistique'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mobile1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mobile2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mobile3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
