# Generated by Django 4.2.5 on 2024-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0014_store_mobile1_store_mobile2_store_mobile3'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='monnaie',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
