# Generated by Django 4.2.5 on 2024-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0016_store_nadherent'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
