# Generated by Django 4.2.5 on 2024-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0018_store_raisonsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='registreCom',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
