# Generated by Django 4.2.5 on 2024-12-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0013_client_valide'),
        ('reglements', '0003_initial'),
        ('produits', '0008_product_parent_product'),
        ('inventory', '0009_bonretourancien_regler_valide'),
        ('ventes', '0036_produitsenavoira_name'),
        ('clientInfo', '0002_initial'),
        ('user', '0013_customuser_adresse_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivageBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, verbose_name='id Bon')),
                ('date_update', models.DateField()),
                ('dateBon', models.DateField()),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agenceLivraison', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('fraisLivraison', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fraisLivraisonexterne', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('note', models.TextField(default='')),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('modifiable', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=True)),
                ('livre', models.BooleanField(default=False)),
                ('typebl', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reference_pc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name_pc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.banque')),
                ('bon_sortie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_sortie_archive', to='ventes.bonsortie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.client')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reglements.echeancereglement')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot')),
                ('mode_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_bonsortie', to='user.customuser')),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivageProduitsEnBonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.TextField(default='')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.bonsortie')),
                ('bon_archiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_archivageBL', to='archivage.archivagebonsortie')),
                ('entrepot', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot')),
                ('produitsenbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_archivage', to='ventes.produitsenbonsortie')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.product')),
            ],
        ),
    ]
