# Generated by Django 4.2.5 on 2024-12-25 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0003_initial'),
        ('tiers', '0013_client_valide'),
        ('produits', '0008_product_parent_product'),
        ('user', '0013_customuser_adresse_ip'),
        ('ventes', '0038_avoirventeancien_bonretour'),
        ('clientInfo', '0002_initial'),
        ('archivage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivageFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField()),
                ('codeFacture', models.CharField(max_length=200, unique=True)),
                ('date_facture', models.DateField()),
                ('date_reglement', models.DateField(default=datetime.datetime.now)),
                ('num_cheque_reglement', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('Remise', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('etat_reglement', models.CharField(choices=[('en Attente', 'en Attente'), ('Règlement Reçu', 'Règlement Reçu'), ('Expédié', 'Expédié'), ('Facture', 'Facture'), ('Facture Comptabilisé', 'Facture Comptabilisé')], max_length=30)),
                ('shippingCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('regle', models.BooleanField(default=False)),
                ('BonS', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.bonsortie')),
                ('banque_Reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.banque')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiers.client')),
                ('echeance_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reglements.echeancereglement')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.facture')),
                ('mode_reglement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reglements.modereglement')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivageProduitsEnFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('FactureNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.facture')),
                ('facture_archiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_facture_archive', to='archivage.archivagefacture')),
                ('produitsfacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.produitsenfacture')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.product')),
            ],
        ),
    ]
