# Generated by Django 4.2.5 on 2024-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlsEnRequeteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('chauffeur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_depart', models.DateTimeField()),
                ('adresse_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('frais_Livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dateTimeAffectation', models.DateTimeField(blank=True, null=True)),
                ('dateTimeDebut', models.DateTimeField(blank=True, null=True)),
                ('dateTimeFin', models.DateTimeField(blank=True, null=True)),
                ('typeCourse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transporteur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fraisTransport', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('montantrecupere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tempsCourse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheLivraisonExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transporteur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numeroColis', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datePrep', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('livre', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReglementTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='requeteclientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReq', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
