# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_customgroup_store_customuser_employeeat_equipe_store'),
        ('tiers', '0001_initial'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlsEnRequeteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('chauffeur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_depart', models.DateTimeField()),
                ('adresse_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('frais_Livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('etat_livraison', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dateTimeAffectation', models.DateTimeField(blank=True, null=True)),
                ('dateTimeDebut', models.DateTimeField(blank=True, null=True)),
                ('dateTimeFin', models.DateTimeField(blank=True, null=True)),
                ('typeCourse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('transporteur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('fraisTransport', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('montantrecupere', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('tempsCourse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FicheLivraisonExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transporteur', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numeroColis', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreparationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('datePrep', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='requeteclientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReq', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('modePaiement', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_requetes', to='tiers.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('bon_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_bontransport', to='logistique.bontransport')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('livre', models.BooleanField(default=False)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transport', to='logistique.bontransport')),
            ],
        ),
    ]
