# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('produits', '0001_initial'),
        ('logistique', '0001_initial'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbontransport',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transport', to='produits.product'),
        ),
        migrations.AddField(
            model_name='preparationstock',
            name='bonEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsE_preparation', to='inventory.bonentry'),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_moyenstransport', to='clientInfo.store'),
        ),
    ]
