# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiers', '0001_initial'),
        ('clientInfo', '0002_initial'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeteclientinfo',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_requetes', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='reglementtransport',
            name='bon_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglements_bontransport', to='logistique.bontransport'),
        ),
        migrations.AddField(
            model_name='reglementtransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
