# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
        ('tiers', '0001_initial'),
        ('user', '0004_customgroup_store_customuser_employeeat_equipe_store'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
        ('logistique', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselivraison',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonL_course', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='courselivraison',
            name='chauffeur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_courses', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='courselivraison',
            name='moyen_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='logistique.moyentransport'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_transports', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_bonstransport', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='moyen_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.moyentransport'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bontransport', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bonstransport', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='blsenrequeteclient',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_requests', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='blsenrequeteclient',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_enreq', to='logistique.requeteclientInfo'),
        ),
    ]
