# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_initial'),
        ('clientInfo', '0002_initial'),
        ('user', '0001_initial'),
        ('tiers', '0001_initial'),
        ('ventes', '0001_initial'),
        ('produits', '0001_initial'),
        ('logistique', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglementtransport',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
        ),
        migrations.AddField(
            model_name='produitsenbontransport',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transport', to='logistique.bontransport'),
        ),
        migrations.AddField(
            model_name='produitsenbontransport',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transport', to='produits.product'),
        ),
        migrations.AddField(
            model_name='preparationstock',
            name='bonEntry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsE_preparation', to='inventory.bonentry'),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_moyenstransport', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='courselivraison',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonL_course', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='courselivraison',
            name='chauffeur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_courses', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='courselivraison',
            name='moyen_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='logistique.moyentransport'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_transports', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_bonstransport', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='moyen_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.moyentransport'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bontransport', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransport',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bonstransport', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='blsenrequeteclient',
            name='bonlivraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_requests', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='blsenrequeteclient',
            name='requete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonsL_enreq', to='logistique.requeteclientinfo'),
        ),
    ]
