# Generated by Django 4.2.5 on 2024-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bontransport',
            name='etat_livraison',
        ),
    ]
