# Generated by Django 4.2.5 on 2024-12-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0004_remove_bontransport_etat_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontransport',
            name='etat_livraison',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
