# Generated by Django 4.2.5 on 2024-12-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0001_initial'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetcredit',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
