# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenfactureachat',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_achat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsencreditnote',
            name='Credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_creditNote', to='achats.creditnote'),
        ),
        migrations.AddField(
            model_name='produitsencreditnote',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_creditNote', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreception',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reception', to='achats.bonreception'),
        ),
        migrations.AddField(
            model_name='produitsenbonreception',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_commandeachat', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='produitsenboncommandesachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonachat',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_achat', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='produitsenbonachat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_achat', to='produits.product'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_facture', to='achats.bonachat'),
        ),
    ]
