# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('achats', '0002_initial'),
        ('tiers', '0001_initial'),
        ('reglements', '0001_initial'),
        ('user', '0004_customgroup_store_customuser_employeeat_equipe_store'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_facture_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='livraison',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factureachat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_factureachat', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='factureachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_facture_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='banque_domiciliation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_banque', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='bon_commande',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_commandes', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_expedition', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='BonCommande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_achat_commande', to='achats.boncommandeachat'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='banque_Reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banque_dossierachat', to='tiers.banque'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_dossier_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_dossier_achat', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='dossierachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_dossier_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='Projet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bon_achats_credit', to='achats.projetcredit'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_creditd', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='BonAchat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsachat_bonreception', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonreception', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='expedition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_bonreception', to='achats.expedition'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='unite_monitaire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitemonitaire_bonreception', to='clientInfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='bonreception',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reception', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_commandeachat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='livraison',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='mode_reglement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_commandesachat', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='boncommandeachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_commandesachats', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='echeance_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonachatt_reglements_echeance', to='reglements.echeancereglement'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonachat', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_achat', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonachat_reglements_type', to='reglements.modereglement'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='monnaie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monnaie_bonachat', to='clientInfo.valeurdevise'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_achat', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonachat',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_achat', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='avoirachat',
            name='BonSortieAssocie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_bonachat', to='achats.bonachat'),
        ),
        migrations.AddField(
            model_name='avoirachat',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avoirs_fournisseur', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='avoirachat',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
    ]
