# Generated by Django 4.2.5 on 2024-11-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BonMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('garantie', models.BooleanField(blank=True, default=False, null=True)),
                ('reponse', models.TextField(blank=True, default='', null=True)),
                ('decision', models.TextField(blank=True, default='', null=True)),
                ('observation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonReforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BonReintegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BonRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('reception_valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonRetourAncien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('bonL', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bonsortiedestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('num_doc', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date_doc_Sortie', models.DateField(blank=True, null=True)),
                ('num_constat', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date_constat', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('automatiquement', models.BooleanField(blank=True, default=False, null=True)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
                ('validation_recu', models.BooleanField(blank=True, default=True, null=True)),
                ('annule', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonTransfertMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBon', models.CharField(max_length=200, unique=True, verbose_name='id Bon')),
                ('dateBon', models.DateField()),
                ('automatiquement', models.BooleanField(blank=True, default=False, null=True)),
                ('valide', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ville', models.CharField(max_length=100)),
                ('codePostal', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='equipeInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_equipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InventaireAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeInv', models.CharField(max_length=100)),
                ('dateInv', models.DateField()),
                ('datecloture', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='produitEnInventaireAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonEchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='media/document')),
                ('image2', models.FileField(upload_to='media/document')),
                ('image3', models.FileField(upload_to='media/document')),
                ('image4', models.FileField(upload_to='media/document')),
                ('quantity', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonReforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('observation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonReintegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reintegrated', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='media/document')),
                ('warranty', models.BooleanField(default=False)),
                ('numseries', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('direction', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonRetourAncien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceproduit', models.CharField(max_length=100)),
                ('nomproduit', models.CharField(max_length=100)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reintegrated', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='media/document')),
                ('warranty', models.BooleanField(default=False)),
                ('numseries', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonSortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnBonTransfertMag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_initial', models.PositiveIntegerField(default=0)),
                ('quantity_pc', models.PositiveIntegerField(default=0)),
                ('quantity_kit', models.PositiveIntegerField(default=0)),
                ('quantity_blocked', models.PositiveIntegerField(default=0)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.entrepot')),
            ],
        ),
    ]
