# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0001_initial'),
        ('inventory', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_stock', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transfertMag', to='inventory.bontransfertmagasin'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='stock_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_recu', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='stock_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_arrive', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transfert', to='inventory.bontransfert'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='stock_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfert_recu', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='stock_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfert_arrive', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbonsortiestock',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_sortie_stock', to='inventory.bonsortiedestock'),
        ),
        migrations.AddField(
            model_name='produitsenbonsortiestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_sorties_stock', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonretourancien',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retourancien', to='inventory.bonretourancien'),
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retour', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreintegration',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reintegration', to='inventory.bonreintegration'),
        ),
        migrations.AddField(
            model_name='produitsenbonreintegration',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_reintegration', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreforme',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reforme', to='inventory.bonreforme'),
        ),
        migrations.AddField(
            model_name='produitsenbonreforme',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reforme', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_maintenance', to='inventory.bonmaintenance'),
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonentry',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_entry', to='inventory.bonentry'),
        ),
        migrations.AddField(
            model_name='produitsenbonentry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_entry', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonechange',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_echange', to='inventory.bonechange'),
        ),
        migrations.AddField(
            model_name='produitsenbonechange',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_echange', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produiteninventaireannuel',
            name='Equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_produits', to='inventory.equipeinventaire'),
        ),
        migrations.AddField(
            model_name='produiteninventaireannuel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_inventaire', to='produits.product'),
        ),
        migrations.AddField(
            model_name='inventaireannuel',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_inventaire', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='inventaireannuel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventaires', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='equipeinventaire',
            name='inv_annuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire_assosiated', to='inventory.inventaireannuel'),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_entrepot', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='entrepot_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entarr_transfertmag', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='entrepot_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entdep_transfertmag', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_arr', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_dep', to='clientInfo.store'),
        ),
    ]
