# Generated by Django 5.1.4 on 2024-12-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0002_initial'),
        ('comptoire', '0002_initial'),
        ('inventory', '0002_initial'),
        ('produits', '0001_initial'),
        ('tiers', '0001_initial'),
        ('user', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonechange',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_echange', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='fournisseur',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_bons_entry', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_entry', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonLComptoir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonmaintenanceComptoir', to='comptoire.bonretourcomptoir'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_maintenance', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_reforme', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reforme', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reintegration', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonRetours', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_retour', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_retour', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='bonRetour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonretour_bons_reintegration', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='bonretour',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bonretour_bon_reforme', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonechange', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_retour_ancien', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour_ancien', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretourancien'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='Client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsBl_sortiesstock', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_sortiesstock', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transfert', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_arr', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='store_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_mag_dep', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transfert_mag', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_entrepot', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='entrepot_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entarr_transfertmag', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='entrepot_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entdep_transfertmag', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='entrepot_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_rec', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='entrepot_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_env', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_sortiesstock', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_retourancien', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_reintegration', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bons_reforme', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsmaintenance', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_entry', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsechange', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='inventaireannuel',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_inventaire', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='inventaireannuel',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventaires', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='equipeinventaire',
            name='inv_annuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire_assosiated', to='inventory.inventaireannuel'),
        ),
        migrations.AddField(
            model_name='produiteninventaireannuel',
            name='Equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_produits', to='inventory.equipeinventaire'),
        ),
        migrations.AddField(
            model_name='produiteninventaireannuel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_inventaire', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonechange',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_echange', to='inventory.bonechange'),
        ),
        migrations.AddField(
            model_name='produitsenbonechange',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_echange', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonentry',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_entry', to='inventory.bonentry'),
        ),
        migrations.AddField(
            model_name='produitsenbonentry',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_entry', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_maintenance', to='inventory.bonmaintenance'),
        ),
        migrations.AddField(
            model_name='produitsenbonmaintenance',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreforme',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reforme', to='inventory.bonreforme'),
        ),
        migrations.AddField(
            model_name='produitsenbonreforme',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reforme', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonreintegration',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_reintegration', to='inventory.bonreintegration'),
        ),
        migrations.AddField(
            model_name='produitsenbonreintegration',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_reintegration', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retour', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='produitsenbonretour',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbonretourancien',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_retourancien', to='inventory.bonretourancien'),
        ),
        migrations.AddField(
            model_name='produitsenbonsortiestock',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_sortie_stock', to='inventory.bonsortiedestock'),
        ),
        migrations.AddField(
            model_name='produitsenbonsortiestock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_sorties_stock', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transfert', to='inventory.bontransfert'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='BonNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bon_transfertMag', to='inventory.bontransfertmagasin'),
        ),
        migrations.AddField(
            model_name='stock',
            name='entrepot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mon_stock', to='produits.product'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='stock_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_recu', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfertmag',
            name='stock_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfertmag_arrive', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='stock_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfert_recu', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='produitsenbontransfert',
            name='stock_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_transfert_arrive', to='inventory.stock'),
        ),
    ]
