# Generated by Django 4.2.5 on 2024-12-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientInfo', '0002_initial'),
        ('user', '0001_initial'),
        ('tiers', '0001_initial'),
        ('ventes', '0001_initial'),
        ('inventory', '0002_initial'),
        ('comptoire', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontransfertmagasin',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transfert_mag', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='entrepot_arrive',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_rec', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='entrepot_depart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bontransfert_env', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bontransfert',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_transfert', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='Client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='bonL',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonsBl_sortiesstock', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='entrepot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_sortiesstock', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonsortiedestock',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_sortiesstock', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_retourancien', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_retour_ancien', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonretourancien',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour_ancien', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonRetours', to='ventes.bonsortie'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_retour', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_retour', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonretour',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_retour', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='bonRetour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonretour_bons_reintegration', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='entrepot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_reintegration', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonreintegration',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reintegration', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='bonretour',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bonretour_bon_reforme', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bons_reforme', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_reforme', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonreforme',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_reforme', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonLComptoir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MesbonmaintenanceComptoir', to='comptoire.bonretourcomptoir'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='bonR',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonmaintenance', to='inventory.bonretourancien'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsmaintenance', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_maintenance', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonmaintenance',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_maintenance', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='entrepot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Entrepots_bons_entry', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='fournisseur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs_bons_entry', to='tiers.fournisseur'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='store',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonentry',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_entry', to='user.customuser'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='bonL',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesbonechange', to='inventory.bonretour'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_echange', to='tiers.client'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='entrepot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepot_bonsechange', to='inventory.entrepot'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_bons_echange', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='bonechange',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_bons_echange', to='user.customuser'),
        ),
    ]
