# Generated by Django 4.2.5 on 2024-12-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity_blocked',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_initial',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_kit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity_pc',
        ),
    ]
