# Generated by Django 4.2.5 on 2024-12-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stock_quantity_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_pc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
