# Generated by Django 4.2.5 on 2024-12-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stock_quantity_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretourancien',
            name='regler_valide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
