# Generated by Django 4.2.5 on 2024-12-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_bonretourancien_regler_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonretour',
            name='bonL',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='reception_valide',
        ),
        migrations.RemoveField(
            model_name='bonretour',
            name='valide',
        ),
    ]
