# Generated by Django 4.2.5 on 2024-12-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0013_client_valide'),
        ('inventory', '0011_bonretour_bonl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretour',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bons_retour', to='tiers.client'),
        ),
    ]
