# Generated by Django 4.2.5 on 2024-12-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_bonretour_reception_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretour',
            name='regler_valide',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
