# Generated by Django 4.2.5 on 2024-12-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_bonretour_regler_valide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenbonretour',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='produitsenbonretour',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produitsenbonretour',
            name='numseries',
        ),
        migrations.RemoveField(
            model_name='produitsenbonretour',
            name='reintegrated',
        ),
        migrations.RemoveField(
            model_name='produitsenbonretour',
            name='warranty',
        ),
    ]
