# Generated by Django 4.2.5 on 2024-12-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_produitsenbonretour_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretour',
            name='reintegrated',
            field=models.BooleanField(default=False),
        ),
    ]
