# Generated by Django 4.2.5 on 2024-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_produitsenbonretour_reintegrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretour',
            name='numseries',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
