# Generated by Django 4.2.5 on 2024-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_produitsenbonretour_numseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretour',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
    ]
