# Generated by Django 4.2.5 on 2024-12-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_produitsenbonretour_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretour',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
