# Generated by Django 4.2.5 on 2024-12-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_produitsenbonretour_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonretour',
            name='image',
            field=models.FileField(null=True, upload_to='media/document'),
        ),
    ]
