# Generated by Django 4.2.5 on 2024-12-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonsortie',
            name='agenceLivraison',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='echeance_reglement',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='fraisLivraison',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='fraisLivraisonexterne',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='mode_reglement',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='modifiable',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='name_pc',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='reference_pc',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='bonsortie',
            name='typebl',
        ),
    ]
