# Generated by Django 4.2.5 on 2024-12-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglements', '0003_initial'),
        ('ventes', '0003_bonsortie_echeance_reglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='mode_reglement',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonL_reglements_type', to='reglements.modereglement'),
        ),
    ]
