# Generated by Django 4.2.5 on 2024-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_bonsortie_mode_reglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='agenceLivraison',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
    ]
