# Generated by Django 4.2.5 on 2024-12-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0005_bonsortie_agencelivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='fraisLivraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
