# Generated by Django 4.2.5 on 2024-12-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_bonsortie_fraislivraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='modifiable',
            field=models.BooleanField(default=False),
        ),
    ]
