# Generated by Django 4.2.5 on 2024-12-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0009_bonsortie_name_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='reference_pc',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
