# Generated by Django 4.2.5 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0010_bonsortie_reference_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='livre',
            field=models.BooleanField(default=False),
        ),
    ]
