# Generated by Django 4.2.5 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_bonsortie_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='typebl',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
