# Generated by Django 4.2.5 on 2024-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_bonsortie_typebl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
