# Generated by Django 4.2.5 on 2024-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0014_bonsortie_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
