# Generated by Django 4.2.5 on 2024-12-23 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0015_bonsortie_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenbonsortie',
            name='kit',
        ),
    ]
