# Generated by Django 4.2.5 on 2024-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0016_remove_produitsenbonsortie_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbonsortie',
            name='kit',
            field=models.TextField(default=''),
        ),
    ]
