# Generated by Django 4.2.5 on 2024-12-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0017_produitsenbonsortie_kit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='mode_reglement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='totalPrice',
        ),
    ]
