# Generated by Django 4.2.5 on 2024-12-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0018_remove_facture_mode_reglement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
