# Generated by Django 4.2.5 on 2024-12-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0020_facture_mode_reglement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenfacture',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='produitsenfacture',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='produitsenfacture',
            name='unitprice',
        ),
    ]
