# Generated by Django 4.2.5 on 2024-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0021_remove_produitsenfacture_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenfacture',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
