# Generated by Django 4.2.5 on 2024-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0023_produitsenfacture_unitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenfacture',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
