# Generated by Django 4.2.5 on 2024-12-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0024_produitsenfacture_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoirvente',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='avoirvente',
            name='motif',
        ),
    ]
