# Generated by Django 4.2.5 on 2024-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0026_avoirvente_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoirvente',
            name='motif',
            field=models.CharField(default='', max_length=200),
        ),
    ]
