# Generated by Django 4.2.5 on 2024-12-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0028_remove_bongarantie_tps_ecoule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bongarantie',
            name='tps_ecoule',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
