# Generated by Django 4.2.5 on 2024-12-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0029_bongarantie_tps_ecoule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenbongarantie',
            name='livre',
        ),
        migrations.RemoveField(
            model_name='produitsenbongarantie',
            name='quantity',
        ),
    ]
