# Generated by Django 4.2.5 on 2024-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0030_remove_produitsenbongarantie_livre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbongarantie',
            name='livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produitsenbongarantie',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
