# Generated by Django 4.2.5 on 2024-12-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0031_produitsenbongarantie_livre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenbongarantie',
            name='livre',
        ),
    ]
