# Generated by Django 4.2.5 on 2024-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0032_remove_produitsenbongarantie_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenbongarantie',
            name='livre',
            field=models.BooleanField(default=False),
        ),
    ]
