# Generated by Django 4.2.5 on 2024-12-23 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0002_initial'),
        ('tiers', '0013_client_valide'),
        ('ventes', '0033_produitsenbongarantie_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoirVenteAncien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonsortie', models.CharField(max_length=200)),
                ('codeAvoir', models.CharField(max_length=200)),
                ('bonretour', models.CharField(blank=True, max_length=200, null=True)),
                ('dateEmission', models.DateField(default=datetime.datetime.now)),
                ('motif', models.CharField(default='', max_length=200)),
                ('montant', models.CharField(default='', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoirsA_client', to='tiers.client')),
                ('store', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='produitsEnAvoirA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referance', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
                ('UnitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('avoir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_avoirA', to='ventes.avoirventeancien')),
            ],
        ),
        migrations.CreateModel(
            name='produitsEnAvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('UnitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('avoir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_avoir', to='ventes.avoirvente')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventes.produitsenbonsortie')),
            ],
        ),
    ]
