# Generated by Django 4.2.5 on 2024-12-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0034_avoirventeancien_produitsenavoira_produitsenavoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitsenavoira',
            name='name',
        ),
    ]
