# Generated by Django 4.2.5 on 2024-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0035_remove_produitsenavoira_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitsenavoira',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
