# Generated by Django 4.2.5 on 2024-12-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0036_produitsenavoira_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoirventeancien',
            name='bonretour',
        ),
    ]
