# Generated by Django 4.2.5 on 2024-12-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0037_remove_avoirventeancien_bonretour'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoirventeancien',
            name='bonretour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
