# Generated by Django 4.2.5 on 2025-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0038_avoirventeancien_bonretour'),
    ]

    operations = [
        migrations.AddField(
            model_name='avoirvente',
            name='bonretour',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
