# Generated by Django 4.2.5 on 2024-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustompermission',
            name='action',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('delat', 'delat'), ('update', 'update')], default='get', max_length=50),
        ),
    ]
