# Generated by Django 4.2.5 on 2024-12-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresse_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entrepots_responsible',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='equipe_affiliated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
