# Generated by Django 4.2.5 on 2024-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercustompermission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustompermission',
            name='action',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('delete', 'delete'), ('update', 'update')], default='get', max_length=50),
        ),
    ]
