# Generated by Django 4.2.5 on 2024-11-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientInfo', '0001_initial'),
        ('user', '0003_cordinates_customgroup_customuser_equipe_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_groupes', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='EmployeeAt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_employees', to='clientInfo.store'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_equipes', to='clientInfo.store'),
        ),
    ]
