# Generated by Django 4.2.5 on 2024-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usercustompermission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustompermission',
            name='action',
            field=models.CharField(choices=[('get', 'get'), ('post', 'post'), ('delete', 'delete'), ('put', 'put')], default='get', max_length=50),
        ),
    ]
