# Generated by Django 4.2.5 on 2024-12-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usercustompermission_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='custom_permissions',
        ),
    ]
