# Generated by Django 4.2.5 on 2024-12-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customuser_equipe_affiliated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True),
        ),
    ]
