# Generated by Django 4.2.5 on 2024-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customgroup_custom_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='custom_permissions',
            field=models.ManyToManyField(blank=True, to='user.usercustompermission'),
        ),
    ]
