# Generated by Django 4.2.5 on 2024-12-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customgroup_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permission',
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='user.usercustompermission'),
        ),
    ]
