# Generated by Django 4.2.5 on 2024-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_adresse_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='adresse_ip',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='entrepots_responsible',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='equipe_affiliated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
