# Generated by Django 4.2.5 on 2024-12-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_customuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
