# Generated by Django 4.2.5 on 2024-12-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_initial'),
        ('user', '0010_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entrepots_responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='inventory.entrepot'),
        ),
    ]
