# Generated by Django 4.2.5 on 2024-12-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_customuser_adresse_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='custom_permissions',
        ),
        migrations.RemoveField(
            model_name='usercustompermission',
            name='view',
        ),
        migrations.AddField(
            model_name='customgroup',
            name='permissions_groupe',
            field=models.ManyToManyField(null=True, to='user.groupepermission'),
        ),
        migrations.AddField(
            model_name='usercustompermission',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_permissions', to='user.groupepermission'),
        ),
    ]
