# Generated by Django 4.2.5 on 2024-12-03 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
        ('clientInfo', '0002_compteentreprise_agence_compteentreprise_banque'),
        ('inventory', '0003_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeOrdre', models.CharField(max_length=255)),
                ('entrepot_destocker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordre_fabrication_destock', to='inventory.entrepot')),
                ('entrepot_stocker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordre_fabrication_stock', to='inventory.entrepot')),
                ('pc_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordre_creation', to='produits.product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientInfo.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsEnOrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('BonNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_ordre_fabrication', to='production.ordrefabrication')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_fabriquation', to='produits.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitProductionFac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ProdPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_fac', to='production.produitsenordrefabrication')),
                ('ProdenFa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_Ordre', to='ventes.produitsenfacture')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitProductionBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ProdPid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_bl', to='production.produitsenordrefabrication')),
                ('ProdenBL', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_en_PEnOrdre', to='ventes.produitsenbonsortie')),
            ],
        ),
    ]
