name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v4

      - name: Check Git version
        run: git --version

      - name: List directory contents
        run: ls -la

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.3

      - name: Install pre-commit
        run: poetry install pre-commit

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint
        
      - name: Test
        run: make test
        env:
          CORESETTING_DATABASES: '{"default":{"HOST":"db"}}'
          CORESETTING_LOCAL_SETTINGS_PATH: "./erp/core/settings/templates/settings.github.py"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
