name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH

      - name: Add Poetry to PATH
        run: echo "${{ github.workspace }}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Ensure the correct path for Poetry is used
          source $GITHUB_PATH
          poetry install
          make install-pre-commit

      - name: Lint
        run: make lint

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h db -U ${{ secrets.POSTGRES_USER }}; then
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Test
        run: make test
        env:
          CORESETTING_DATABASES: '{"default":{"HOST":"db"}}'
          CORESETTING_LOCAL_SETTINGS_PATH: "./erp/core/settings/templates/settings.github.py"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
