name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: erp
          POSTGRES_PASSWORD: erpPassword
          POSTGRES_DB: erp
          options: >-
            --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}"
            --health-interval=5s
            --health-timeout=5s
            --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Run Poetry image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.3

      - name: Install dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint
      - name: Test
        run: make test
        env:
          CORESETTING_DATABASES: '{"default":{"HOST":"db"}}'
          CORESETTING_LOCAL_SETTINGS_PATH: "./erp/core/settings/templates/settings.github.py"
