name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-slim
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y make libpq-dev 

      - name: Install Poetry
        run: python3 -m pip install --upgrade pip && python3 -m pip install poetry==1.8.3

      - name: Install dependencies
        run:
            poetry add psycopg2-binary --dev
            make install && make install-pre-commit

      - name: Lint
        run: make lint
