name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-slim
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pipx and add it to PATH
        run: |
          python3 -m pip install --user pipx
          export PATH="$PATH:/github/home/.local/bin"  # Manually add pipx to PATH

      - name: Install Poetry
        run: pipx install poetry==1.8.3  # Now pipx should be in PATH

      - name: Install dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint
