name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12-slim
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y make libpq-dev gcc git

      - name: Install Poetry
        run: python3 -m pip install --upgrade pip && python3 -m pip install poetry==1.8.3

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-root  # Skips trying to install the non-existent backend package

      - name: Set up Git for pre-commit
        run: |
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install and run pre-commit hooks
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files

      - name: Lint
        run: make lint
